# -*- coding: utf-8 -*-
"""Check_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNOOlXO8SU7KS4K00Fzdqlau8rSF2U0s
"""

import requests
import pandas as pd
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor
import getpass
import re

class NewsenseScanner:
    def __init__(self, base_url, user, password):
        self.base_url = base_url.rstrip('/')
        self.user = user
        self.password = password
        self.token = None
        self.login()

    def login(self):
        url = f"{self.base_url}/auth/login"
        try:
            resp = requests.post(url, json={"username": self.user, "password": self.password})
            resp.raise_for_status()
            self.token = resp.json()["token"]
            print("✅ Đăng nhập Newsense thành công!")
        except Exception as e:
            print(f"❌ Đăng nhập thất bại: {e}")

    def get_all_devices(self):
        """Lấy tất cả thiết bị có trong tài khoản."""
        headers = {"X-Authorization": f"Bearer {self.token}"}
        devices = []
        page = 0
        while True:
            url = f"{self.base_url}/tenant/devices?pageSize=100&page={page}"
            resp = requests.get(url, headers=headers)
            data = resp.json()
            for d in data.get("data", []):
                devices.append({"id": d["id"]["id"], "name": d["name"]})
            if not data.get("hasNextPage"):
                break
            page += 1
        return devices

    def get_device_keys(self, device_id):
        """Lấy tất cả các tên biến (keys) của một thiết bị."""
        headers = {"X-Authorization": f"Bearer {self.token}"}
        url = f"{self.base_url}/plugins/telemetry/DEVICE/{device_id}/keys/timeseries"
        try:
            resp = requests.get(url, headers=headers)
            return resp.json() if resp.status_code == 200 else []
        except:
            return []

    def get_latest_telemetry(self, device_id, device_name, keys, time_delay_seconds):
        """Lấy timestamp mới nhất cho tất cả keys của 1 thiết bị."""
        if not keys: return []

        headers = {"X-Authorization": f"Bearer {self.token}"}
        keys_str = ",".join(keys)
        url = f"{self.base_url}/plugins/telemetry/DEVICE/{device_id}/values/timeseries?keys={keys_str}&limit=1"

        results = []
        try:
            resp = requests.get(url, headers=headers)
            data = resp.json()
            now = datetime.now(timezone.utc)

            for key in keys:
                if key in data and len(data[key]) > 0:
                    last_ts = data[key][0]['ts']
                    last_time = datetime.fromtimestamp(last_ts / 1000, tz=timezone.utc)
                    diff = now - last_time

                    # Trạng thái dựa trên số giây đã parse
                    status = "🟢 Active" if diff.total_seconds() < time_delay_seconds else "🔴 Stopped"

                    results.append({
                        "Device Name": device_name,
                        "Variable (Key)": key,
                        "Last Update": last_time.astimezone().strftime('%Y-%m-%d %H:%M:%S'),
                        "Delay": f"{diff.days}d {diff.seconds//3600}h {(diff.seconds%3600)//60}m",
                        "Status": status
                    })
                else:
                    results.append({
                        "Device Name": device_name,
                        "Variable (Key)": key,
                        "Last Update": "Never",
                        "Delay": "N/A",
                        "Status": "⚪ No Data"
                    })
        except Exception as e:
            print(f"⚠️ Lỗi khi quét {device_name}: {e}")
        return results

def parse_delay(delay_str):
    """
    Chuyển đổi chuỗi format (1s, 5m, 2h, 1d) sang giây.
    """
    delay_str = delay_str.lower().strip()
    match = re.match(r"(\d+)\s*([smhd])?", delay_str)
    if not match:
        return 3600 # Mặc định 1 giờ nếu nhập sai

    value, unit = match.groups()
    value = int(value)

    multipliers = {
        's': 1,
        'm': 60,
        'h': 3600,
        'd': 86400
    }
    return value * multipliers.get(unit, 1) # Mặc định là giây nếu không có đơn vị

def run_system_audit():
    print("--- CẤU HÌNH QUÉT HỆ THỐNG NEWSENSE ---")
    USER = input("Tên đăng nhập: ")
    PASS = getpass.getpass("Mật khẩu (sẽ không hiển thị): ")
    BASE_URL = "https://newsense.viphap.com/api"

    print("\nNhập thời gian trễ tối đa cho phép (Ví dụ: 30s, 15m, 2h, 1d)")
    raw_delay = input("Thời gian delay: ")
    delay_seconds = parse_delay(raw_delay)

    scanner = NewsenseScanner(BASE_URL, USER, PASS)
    if not scanner.token: return

    print(f"\n🚀 Bắt đầu quét toàn bộ hệ thống (Ngưỡng: {delay_seconds} giây)...")
    all_devices = scanner.get_all_devices()
    print(f"📦 Tìm thấy {len(all_devices)} thiết bị.")

    all_report_data = []

    def process_device(device):
        keys = scanner.get_device_keys(device['id'])
        return scanner.get_latest_telemetry(device['id'], device['name'], keys, delay_seconds)

    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(process_device, d) for d in all_devices]
        for f in futures:
            all_report_data.extend(f.result())

    df_report = pd.DataFrame(all_report_data)

    if not df_report.empty:
        df_report = df_report.sort_values(by=["Status", "Last Update"], ascending=[True, False])

        print("\n📊 BẢNG TỔNG HỢP TRẠNG THÁI HỆ THỐNG")
        print(df_report.to_string(index=False))

        filename = f"System_Audit_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx"
        df_report.to_excel(filename, index=False)
        print(f"\n✅ Đã xuất báo cáo chi tiết ra file: {filename}")
    else:
        print("❌ Không tìm thấy dữ liệu biến nào để báo cáo.")

if __name__ == "__main__":
    run_system_audit()

