# -*- coding: utf-8 -*-
"""Offline_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BVpZTqy-ypti-9A4Fcnexu6brAlFvVD
"""

# No colab imports
import os
import re
import json
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv
import difflib

# ================================================================
# ⚙️ CONFIG / AUTH
# ================================================================
load_dotenv()

TB_USER = os.getenv("TB_USER", "USER")
TB_PASS = os.getenv("TB_PASS", "PASS")
BASE_URL = os.getenv("BASE_URL") or "https://newsense.viphap.com/api"

# ================================================================
# 🧠 STATE GLOBALS
# ================================================================
kg_df = pd.DataFrame()
_lookup_built = False

# ================================================================
# 🗺️ BUILD LOOKUP TABLES TỪ KNOWLEDGE GRAPH (thay thế Gemini)
# ================================================================
# Tự động đọc tất cả vị trí & loại dữ liệu từ KG — không hardcode

# ================================================================
# 🗺️ NÂNG CẤP MAPPING & EXTRACTION
# ================================================================

def build_lookup_tables(kg_df: pd.DataFrame):
    if kg_df.empty:
        return {}, {}, {}, [], []

    kg_records = kg_df.to_dict(orient="records")

    # 1. Location Map (Giữ nguyên logic cũ nhưng bổ sung clean key)
    location_col = next((c for c in kg_df.columns if "vị trí" in c.lower() or "location" in c.lower()), None)
    location_map = {}
    if location_col:
        for val in kg_df[location_col].dropna().unique():
            val_str = str(val).strip()
            key = val_str.lower()
            location_map[key] = val_str
            # Tách từ để bắt keyword tắt (ví dụ: "đốt sk5" -> bắt "sk5")
            words = key.split()
            if len(words) >= 2:
                location_map[words[-1]] = val_str # Lấy từ cuối (thường là mã đốt)

    # 2. Semantic Type Map (CẬP NHẬT MẠNH MẼ THEO DATA CỦA BẠN)
    # Mapping từ ngôn ngữ tự nhiên -> từ khóa kỹ thuật có trong KG
    SEMANTIC_TYPE_MAP = {
        # Nhiệt độ
        "nhiệt độ": ["nhiệt độ", "temp", "pt100", "nhiệt", "t"],
        "nhiệt":    ["nhiệt độ", "temp", "pt100", "t"],
        "pt100":    ["pt100", "nhiệt độ"],
        
        # Ứng suất / Strain Gauge
        "ứng suất": ["ứng suất", "stress", "strain", "sg", "contrainte", "biến dạng"],
        "strain":   ["strain", "sg", "contrainte"],
        "sg":       ["sg", "strain", "ứng suất", "contrainte"],
        "biến dạng":["biến dạng", "deformation", "strain", "sg"],
        
        # Dao động / Gia tốc
        "dao động": ["dao động", "vibration", "acc", "gia tốc"],
        "rung":     ["rung", "vibration", "acc"],
        "gia tốc":  ["gia tốc", "acc", "acceleration"],
        
        # Chuyển vị / GNSS
        "chuyển vị": ["chuyển vị", "displacement", "gnss", "gps"],
        "lún":       ["lún", "settlement"],
        "gnss":      ["gnss", "gps", "chuyển vị"],
        
        # Môi trường
        "gió":       ["gió", "wind"],
        "mưa":       ["mưa", "rain", "lượng mưa"],
        "độ ẩm":     ["độ ẩm", "humidity"],
    }

    # 3. Exact Var Map (Map chính xác tên biến nếu có)
    var_col = next((c for c in kg_df.columns if "tên biến" in c.lower() or "key" in c.lower()), None)
    type_map = {}
    if var_col:
        for var_val in kg_df[var_col].dropna().unique():
            key = str(var_val).lower().strip()
            type_map[key] = var_val

    # 4. Dynamic Device Types
    type_col = next((c for c in kg_df.columns if "loại" in c.lower()), None)
    dynamic_device_types = []
    if type_col:
        dynamic_device_types = [str(x).lower().strip() for x in kg_df[type_col].dropna().unique()]

    return location_map, SEMANTIC_TYPE_MAP, type_map, dynamic_device_types, kg_records

def extract_data_types(text: str) -> list[str]:
    """
    Nâng cấp: Loại bỏ stopwords và tìm keyword kỹ thuật chính xác hơn.
    """
    text_lower = text.lower()
    
    # Danh sách từ vô nghĩa cần loại bỏ để tránh bắt nhầm
    stopwords = ["của", "tại", "ở", "các", "những", "cái", "xem", "cho", "biết", "về", "trong", "ngày", "tháng", "năm"]
    for w in stopwords:
        text_lower = text_lower.replace(f" {w} ", " ")

    found_patterns = set()

    # 1. Quét Semantic Map (Ưu tiên cao)
    # Ví dụ: user gõ "ứng suất" -> map ra ["sg", "contrainte", "stress"...]
    for keyword, related_terms in semantic_type_map.items():
        if keyword in text_lower:
            found_patterns.update(related_terms)

    # 2. Quét Dynamic Types (Loại thiết bị có sẵn trong KG)
    for dt in dynamic_device_types:
        if dt in text_lower:
            found_patterns.add(dt)

    # 3. Quét Tên biến chính xác (Exact Var Map)
    for keyword, var_name in exact_var_map.items():
        if keyword in text_lower:
            found_patterns.add(str(var_name).lower())

    # 4. Fallback thông minh: Nếu không tìm thấy keyword nào từ map
    # Thử lấy các từ lạ (không phải location, không phải từ phổ thông) làm keyword
    if not found_patterns:
        words = text_lower.split()
        potential_keywords = []
        for w in words:
            # Nếu từ này không nằm trong location_map và dài > 2 ký tự -> có thể là tên thiết bị (ví dụ: P19)
            is_loc = any(w in k for k in location_map.keys())
            if not is_loc and len(w) > 1 and w not in ["kiểm", "tra", "chart", "biểu", "đồ"]:
                potential_keywords.append(w)
        
        # Chỉ thêm vào nếu tìm thấy ít từ (tránh add cả câu)
        if 0 < len(potential_keywords) < 3:
            found_patterns.update(potential_keywords)

    print(f"DEBUG: Keywords extracted -> {list(found_patterns)}")
    return list(found_patterns)

# Globals to store maps
location_map = {}
semantic_type_map = {}
exact_var_map = {}
dynamic_device_types = []
kg_records = []

def ensure_lookups(kg_df_input):
    global kg_df, _lookup_built, location_map, semantic_type_map, exact_var_map, dynamic_device_types, kg_records
    if _lookup_built and kg_df.equals(kg_df_input):
        return
    kg_df = kg_df_input
    location_map, semantic_type_map, exact_var_map, dynamic_device_types, kg_records = build_lookup_tables(kg_df)
    _lookup_built = True

# ================================================================
# 🕓 INTERPRET RELATIVE TIME (giữ nguyên từ bản gốc, đã tốt)
# ================================================================
def interpret_relative_time(query: str):
    now = datetime.now()
    text = query.lower()

    if "hôm nay" in text:
        start = now.replace(hour=0, minute=0, second=0)
        return start.strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

    if "hôm qua" in text:
        yesterday = now - timedelta(days=1)
        return yesterday.strftime("%Y-%m-%d"), yesterday.strftime("%Y-%m-%d")

    m = re.search(r"(\d+)\s*(ngày|tuần|tháng|năm)", text)
    if m:
        n, unit = int(m.group(1)), m.group(2)
        if unit == "ngày":   start = now - timedelta(days=n)
        elif unit == "tuần": start = now - timedelta(weeks=n)
        elif unit == "tháng":start = now - timedelta(days=n * 30)
        elif unit == "năm":  start = datetime(now.year - n + 1, 1, 1)
        return start.strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

    if "tuần này" in text:
        start = (now - timedelta(days=now.weekday())).replace(hour=0, minute=0, second=0)
        return start.strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

    if "tháng này" in text:
        return now.replace(day=1).strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

    if "từ đầu năm" in text:
        return now.replace(month=1, day=1).strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

    if "năm ngoái" in text:
        y = now.year - 1
        return f"{y}-01-01", f"{y}-12-31"

    # Ngày tuyệt đối dạng YYYY-MM-DD
    dates = re.findall(r"\d{4}-\d{2}-\d{2}", text)
    if len(dates) >= 2:
        return dates[0], dates[1]
    if len(dates) == 1:
        return dates[0], now.strftime("%Y-%m-%d")

    # Ngày dạng DD/MM/YYYY
    dates2 = re.findall(r"\d{1,2}/\d{1,2}/\d{4}", text)
    if dates2:
        parsed = [datetime.strptime(d, "%d/%m/%Y").strftime("%Y-%m-%d") for d in dates2]
        return (parsed[0], parsed[1]) if len(parsed) >= 2 else (parsed[0], now.strftime("%Y-%m-%d"))

    # Mặc định: 30 ngày gần nhất
    return (now - timedelta(days=30)).strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")

# ================================================================
# 🔍 OFFLINE NLU ENGINE — thay thế hoàn toàn Gemini cho extraction
# ================================================================
def extract_location(text: str) -> str | None:
    """Tìm vị trí trong câu hỏi bằng fuzzy match với location_map."""
    text_lower = text.lower()

    # 1. Khớp chính xác trước
    for keyword, location in location_map.items():
        if keyword in text_lower:
            return location

    # 2. Fuzzy match nếu không khớp chính xác
    all_keys = list(location_map.keys())
    words = re.findall(r'\w+', text_lower)
    for word in words:
        matches = difflib.get_close_matches(word, all_keys, n=1, cutoff=0.82)
        if matches:
            return location_map[matches[0]]

    return None

def extract_data_types(text: str) -> list[str]:
    """Tìm loại dữ liệu/thiết bị từ câu hỏi bằng Regex & Fuzzy Match."""
    text_lower = text.lower()
    found_patterns = set()

    # 1. Khớp bằng Word Boundary cho SEMANTIC_MAP (Tránh lỗi dính chữ)
    for keyword, patterns in semantic_type_map.items():
        # Dùng regex \b để bắt chính xác từ khóa đứng độc lập
        if re.search(r'\b' + re.escape(keyword) + r'\b', text_lower):
            found_patterns.update(patterns)

    # Nếu không phải là regex keyword chuẩn, kiểm tra dạng fuzzy trong tên thiết bị
    words = text_lower.split()
    for dt in dynamic_device_types:
        if dt in text_lower:
            found_patterns.add(dt)
        else:
            for word in words:
                if difflib.SequenceMatcher(None, word, dt).ratio() > 0.85:
                    found_patterns.add(dt)

    # 3. Khớp chính xác tên biến (nếu người dùng gõ thẳng tên biến)
    for keyword, var_name in exact_var_map.items():
        if keyword in text_lower:
            found_patterns.add(var_name)
            
    # Xóa các từ stopword hoặc keywords dư thừa ra, không trả mảng empty
    if not found_patterns:
        # Nhặt keyword tùy biến nếu query chứa các chuỗi có vẻ như tên loại
        for word in words:
            if word not in ["kiểm", "tra", "tại", "đốt", "các", "thiết", "bị", "ngày", "tháng", "hôm", "nay", "qua"]:
                found_patterns.add(word)

    print(f"DEBUG: Keyword nhận diện được -> {list(found_patterns)}")
    return list(found_patterns)

def filter_devices_from_kg(location: str | None, data_type_patterns: list[str]) -> list[dict]:
    """
    Nâng cấp: Sử dụng cơ chế SCORING (Tính điểm) để lọc thiết bị.
    Thay vì match chính xác 100%, ta tìm thiết bị 'phù hợp nhất'.
    """
    if not kg_records:
        return []

    # Xác định các cột quan trọng trong KG
    cols = {
        "loc": next((c for c in kg_df.columns if "vị trí" in c.lower() or "location" in c.lower()), ""),
        "name": next((c for c in kg_df.columns if "tên thiết bị" in c.lower()), "Tên thiết bị"),
        "var":  next((c for c in kg_df.columns if "tên biến" in c.lower() or "key" in c.lower()), "Tên biến"),
        "type": next((c for c in kg_df.columns if "loại" in c.lower()), "Loại thiết bị"),
        "dev":  next((c for c in kg_df.columns if c.lower() == "device"), "Device")
    }

    candidates = []

    # Chuẩn hóa patterns
    patterns = [str(p).lower().strip() for p in data_type_patterns if str(p).strip()]

    for row in kg_records:
        # Lấy giá trị các trường
        r_loc  = str(row.get(cols["loc"], "")).lower()
        r_name = str(row.get(cols["name"], "")).lower()
        r_var  = str(row.get(cols["var"], "")).lower()
        r_type = str(row.get(cols["type"], "")).lower()
        r_dev  = str(row.get(cols["dev"], "")).lower()

        # 1. Lọc Vị trí (Location Filter) - BẮT BUỘC nếu user có nhập location
        if location:
            # Logic fuzzy nhẹ cho location: "sk5" match "đốt sk5"
            if location.lower() not in r_loc and location.lower() not in r_name:
                continue 

        # 2. Tính điểm khớp keyword (Scoring)
        score = 0
        if not patterns:
            # Nếu user không nhập loại biến (vd: "Kiểm tra SK5") -> Lấy hết -> Score mặc định = 1
            score = 1
        else:
            for p in patterns:
                # Ưu tiên khớp trong Tên biến (Key) hoặc Loại thiết bị
                if p in r_var:  score += 3  # Match 'contrainte' trong 'Contrainte(13)'
                if p in r_type: score += 3  # Match 'sg' trong loại 'sg'
                if p in r_name: score += 1  # Match trong tên hiển thị
                if p in r_dev:  score += 1  # Match trong tên Device cha

        if score > 0:
            candidates.append({
                "data": row,
                "score": score
            })

    # 3. Sắp xếp và chọn lọc
    if not candidates:
        return []

    # Sắp xếp giảm dần theo điểm
    candidates.sort(key=lambda x: x["score"], reverse=True)

    # Nếu có patterns, chỉ lấy những thằng có score cao nhất (tránh lấy rác)
    # Ví dụ: Nếu top 1 là 3 điểm, chỉ lấy những thằng >= 2 điểm
    if patterns:
        best_score = candidates[0]["score"]
        threshold = max(1, best_score - 1) # Cho phép sai số nhẹ
        final_list = [c["data"] for c in candidates if c["score"] >= threshold]
    else:
        # Nếu không có pattern (lấy hết theo location), trả về tất cả kết quả tìm được
        final_list = [c["data"] for c in candidates]

    # Format lại output chuẩn
    results = []
    for item in final_list:
        results.append({
            "Tên thiết bị": item.get(cols["name"], ""),
            "Device": item.get(cols["dev"], ""),
            "Tên biến": item.get(cols["var"], ""),
            "Loại thiết bị": item.get(cols["type"], "")
        })

    return results

def parse_query_offline(query: str) -> dict:
    """
    🔑 HÀM CHÍNH — thay thế hoàn toàn chatbot() + Gemini.
    Phân tích câu hỏi 100% offline, không gọi API.
    """
    text = query.strip()

    # 0. Intent 
    intent = "chart"
    check_keywords = ["kiểm tra", "check", "trạng thái", "status", "hoạt động không", "báo cáo"]
    if any(k in text.lower() for k in check_keywords):
        intent = "check_status"

    # 1. Thời gian
    start_date, end_date = interpret_relative_time(text)

    # 2. Vị trí
    location = extract_location(text)

    # 3. Loại dữ liệu / Thiết bị
    data_type_patterns = extract_data_types(text)
    print(f"DEBUG: parse_query_offline - data_type_patterns from extract_data_types: {data_type_patterns}")

    # 4. Lọc devices từ KG
    devices = filter_devices_from_kg(location, data_type_patterns)
    print(f"DEBUG: parse_query_offline - devices after first filter (with patterns): {devices}")

    # 5. Fallback: Nếu không tìm thấy loại dữ liệu nhưng có vị trí → lấy tất cả
    if not devices and location:
        print(f"   ℹ️  Không rõ loại thiết bị — lấy tất cả biến tại '{location}'")
        devices = filter_devices_from_kg(location, [])
        print(f"DEBUG: parse_query_offline - devices after fallback filter (no patterns): {devices}")

    # Đóng ngoặc result (đoạn code của bạn bị thiếu phần này)
    result = {
        "intent": intent,
        "start_date": start_date,
        "end_date": end_date,
        "location": location,
        "data_type_patterns": data_type_patterns,
        "devices_found": len(devices),
        "devices": devices
    }

    return result

# ================================================================
# 📊 OFFLINE ANALYSIS ENGINE — thay thế Gemini analyze_data()
# ================================================================

# Ngưỡng cảnh báo theo loại biến (tùy chỉnh theo dự án của bạn)
THRESHOLDS = {
    "temperature": {"warn_high": 45, "warn_low": -5,  "unit": "°C"},
    "temp":        {"warn_high": 45, "warn_low": -5,  "unit": "°C"},
    "humidity":    {"warn_high": 95, "warn_low": 20,  "unit": "%"},
    "strain":      {"warn_high": 500, "warn_low": -500,"unit": "με"},
    "sg":          {"warn_high": 500, "warn_low": -500,"unit": "με"},
    "acc":         {"warn_high": 0.5, "warn_low": -0.5,"unit": "g"},
    "vibration":   {"warn_high": 0.5, "warn_low": -0.5,"unit": "g"},
    "rainfall":    {"warn_high": 100, "warn_low": 0,  "unit": "mm"},
    "wind":        {"warn_high": 30,  "warn_low": 0,  "unit": "m/s"},
    "water_level": {"warn_high": 10,  "warn_low": -10, "unit": "m"},
}

def detect_anomalies(df: pd.DataFrame, key_lower: str) -> list[str]:
    """Phát hiện bất thường dựa trên IQR + threshold."""
    alerts = []
    if df.empty or "value" not in df.columns:
        return alerts

    # IQR method
    Q1, Q3 = df["value"].quantile(0.25), df["value"].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df["value"] < Q1 - 2.5 * IQR) | (df["value"] > Q3 + 2.5 * IQR)]
    if len(outliers) > 0:
        alerts.append(f"⚠️  Phát hiện {len(outliers)} điểm bất thường (ngoài IQR×2.5)")

    # Threshold check
    for key_pattern, limits in THRESHOLDS.items():
        if key_pattern in key_lower:
            hi, lo = limits["warn_high"], limits["warn_low"]
            over_high = (df["value"] > hi).sum()
            over_low  = (df["value"] < lo).sum()
            if over_high > 0:
                alerts.append(f"🔴 {over_high} điểm vượt ngưỡng cao ({hi} {limits['unit']})")
            if over_low > 0:
                alerts.append(f"🔵 {over_low} điểm dưới ngưỡng thấp ({lo} {limits['unit']})")
            break

    return alerts

def trend_description(df: pd.DataFrame) -> str:
    """Mô tả xu hướng tăng/giảm/ổn định bằng linear regression đơn giản."""
    if len(df) < 3:
        return "không đủ dữ liệu để phân tích xu hướng"

    x = np.arange(len(df))
    y = df["value"].values
    slope = np.polyfit(x, y, 1)[0]

    std = df["value"].std()
    mean = df["value"].mean()
    cv = (std / mean * 100) if mean != 0 else 0  # Coefficient of variation

    if abs(slope) < 0.001 * abs(mean):
        trend = "ổn định"
    elif slope > 0:
        trend = f"có xu hướng TĂNG nhẹ (+{slope:.4f}/điểm)"
    else:
        trend = f"có xu hướng GIẢM nhẹ ({slope:.4f}/điểm)"

    stability = "biến động cao" if cv > 30 else ("biến động vừa" if cv > 10 else "ổn định")
    return f"{trend}, {stability} (CV={cv:.1f}%)"

def analyze_data_offline(fetched_data_list: list, original_query: str):
    """
    🔑 Phân tích thống kê + phát hiện bất thường + mô tả xu hướng + Lấy giá trị mới nhất.
    """
    print("\n" + "=" * 50)
    print("🔍 PHÂN TÍCH DỮ LIỆU (Offline Engine)")
    print("=" * 50)

    if not fetched_data_list:
        print("   - Không có dữ liệu để phân tích.")
        return

    for item in fetched_data_list:
        df   = item["data"]
        label = item["label"]
        key_lower = label.lower()

        print(f"\n📌 {label}")
        print("   " + "-" * 46)

        if df.empty or "value" not in df.columns:
            print("   ℹ️  Không có dữ liệu.")
            continue

        mean_val = df["value"].mean()
        min_val  = df["value"].min()
        max_val  = df["value"].max()
        std_val  = df["value"].std()
        n        = len(df)

        # --- LẤY GIÁ TRỊ MỚI NHẤT Ở ĐÂY ---
        latest_row = df.iloc[-1]
        latest_val = latest_row["value"]
        latest_ts = latest_row["ts"].strftime('%Y-%m-%d %H:%M:%S')

        # Tìm unit từ THRESHOLDS
        unit = ""
        for k, v in THRESHOLDS.items():
            if k in key_lower:
                unit = v["unit"]
                break

        # Thống kê cơ bản
        print(f"   🟢 MỚI NHẤT       : {latest_val:.3f} {unit} (Cập nhật lúc {latest_ts})")
        print(f"   📊 Số điểm dữ liệu: {n}")
        print(f"   📈 Cao nhất       : {max_val:.3f} {unit}")
        print(f"   📉 Thấp nhất      : {min_val:.3f} {unit}")
        print(f"   〰️  Trung bình     : {mean_val:.3f} {unit}")

        # Thời gian đỉnh
        idx_max = df["value"].idxmax()
        idx_min = df["value"].idxmin()
        print(f"   🕐 Đỉnh cao nhất lúc: {df.loc[idx_max, 'ts'].strftime('%Y-%m-%d %H:%M')}")
        print(f"   🕐 Đỉnh thấp nhất lúc: {df.loc[idx_min, 'ts'].strftime('%Y-%m-%d %H:%M')}")

        # Xu hướng
        trend = trend_description(df)
        print(f"   📡 Xu hướng       : {trend}")

        # Cảnh báo bất thường
        alerts = detect_anomalies(df, key_lower)
        if alerts:
            print("   🚨 Cảnh báo:")
            for a in alerts:
                print(f"      {a}")
        else:
            print("   ✅ Không phát hiện bất thường")

    print("\n" + "=" * 50)

# ================================================================
# 🛑 NEWSENSE CLIENT (giữ nguyên từ bản gốc)
# ================================================================
class NewsenseClient:
    def __init__(self, base_url, username, password):
        self.base_url = base_url.rstrip('/')
        self.username = username
        self.password = password
        self.token = self.login()

    def login(self):
        resp = requests.post(f"{self.base_url}/auth/login",
                             json={"username": self.username, "password": self.password})
        if resp.status_code == 401:
            raise Exception("❌ Sai username hoặc mật khẩu.")
        resp.raise_for_status()
        print("✅ Đăng nhập Newsense thành công.")
        return resp.json().get("token")

    def get_devices(self):
        headers = {"X-Authorization": f"Bearer {self.token}"}
        page, devices = 0, []
        while True:
            resp = requests.get(f"{self.base_url}/tenant/devices", headers=headers,
                                params={"pageSize": 100, "page": page})
            resp.raise_for_status()
            data = resp.json()
            for d in data.get("data", []):
                devices.append({"id": d["id"]["id"], "name": d["name"]})
            if not data.get("hasNextPage"):
                break
            page += 1
        return devices

    def get_timeseries(self, device_id, key, start_date_str, end_date_str):
        headers = {"X-Authorization": f"Bearer {self.token}"}
        url = f"{self.base_url}/plugins/telemetry/DEVICE/{device_id}/values/timeseries"

        try:
            start_dt = datetime.strptime(start_date_str, "%Y-%m-%d").replace(hour=0, minute=0, second=0)
            end_dt   = datetime.strptime(end_date_str,   "%Y-%m-%d").replace(hour=23, minute=59, second=59)
            start_ts = int(start_dt.timestamp() * 1000)
            end_ts   = int(end_dt.timestamp()   * 1000)
        except ValueError:
            print("❌ Định dạng ngày không hợp lệ.")
            return pd.DataFrame()

        duration_days = (end_dt - start_dt).days
        params = {"startTs": start_ts, "endTs": end_ts, "keys": key}

        if duration_days > 90:
            params.update({"interval": 86400000 * 7, "agg": "AVG"})
            print(f"   - Tổng hợp theo TUẦN cho {key}")
        elif duration_days > 7:
            params.update({"interval": 86400000, "agg": "AVG"})
            print(f"   - Tổng hợp theo NGÀY cho {key}")
        else:
            params["limit"] = 10000
            print(f"   - Dữ liệu thô cho {key}")

        resp = requests.get(url, headers=headers, params=params)
        if resp.status_code != 200:
            print(f"⚠️ HTTP {resp.status_code}: {resp.text[:200]}")
            return pd.DataFrame()

        data = resp.json().get(key, [])
        if not data:
            return pd.DataFrame()

        df = pd.DataFrame(data)
        try:
            df["ts"] = pd.to_datetime(df["timestamp"], unit="ms")
        except:
            df["ts"] = pd.to_datetime(df["ts"], unit ="ms")
        df["value"] = pd.to_numeric(df["value"], errors="coerce")
        return df[["ts", "value"]].dropna(subset=["value"])

    def get_latest_telemetry(self, device_id, device_name, keys, time_delay_seconds=3600):
        if not keys: return []

        headers = {"X-Authorization": f"Bearer {self.token}"}
        keys_str = ",".join(keys)
        url = f"{self.base_url}/plugins/telemetry/DEVICE/{device_id}/values/timeseries?keys={keys_str}&limit=1"

        results = []
        try:
            resp = requests.get(url, headers=headers)
            data = resp.json()
            now = datetime.now(timezone.utc)

            for key in keys:
                if key in data and len(data[key]) > 0:
                    last_ts = data[key][0]['ts']
                    last_time = datetime.fromtimestamp(last_ts / 1000, tz=timezone.utc)
                    diff = now - last_time

                    status = "🟢 Active" if diff.total_seconds() < time_delay_seconds else "🔴 Stopped"

                    results.append({
                        "Device Name": device_name,
                        "Variable (Key)": key,
                        "Last Update": last_time.astimezone().strftime('%Y-%m-%d %H:%M:%S'),
                        "Delay": f"{diff.days}d {diff.seconds//3600}h {(diff.seconds%3600)//60}m",
                        "Status": status
                    })
                else:
                    results.append({
                        "Device Name": device_name,
                        "Variable (Key)": key,
                        "Last Update": "Never",
                        "Delay": "N/A",
                        "Status": "⚪ No Data"
                    })
        except Exception as e:
            print(f"⚠️ Lỗi khi quét {device_name}: {e}")
        return results


# ================================================================
# 🔧 INTERFACE FOR STREAMLIT (app.py)
# ================================================================
def chatbot(query: str, kg_df_input: pd.DataFrame, chat_history: list):
    ensure_lookups(kg_df_input)
    parsed = parse_query_offline(query)
    is_latest = ("hiện tại" in query.lower() or "mới nhất" in query.lower())
    result = {
        "intent": parsed.get("intent", "chart"),
        "start_date": parsed.get("start_date"),
        "end_date": parsed.get("end_date"),
        "is_latest": is_latest,
        "devices": parsed.get("devices", [])
    }
    result_str = json.dumps(result, ensure_ascii=False)
    chat_history.append({"role": "model", "content": result_str})
    return result_str, chat_history

def analyze_data(fetched_data_list: list, original_query: str):
    output = []
    output.append("=" * 50)
    output.append("🔍 PHÂN TÍCH DỮ LIỆU (Offline Engine)")
    output.append("=" * 50)
    if not fetched_data_list:
        return "Không có dữ liệu để phân tích."
    for item in fetched_data_list:
        df   = item["data"]
        label = item["label"]
        key_lower = label.lower()
        output.append(f"\n📌 {label}")
        output.append("-" * 46)
        if df.empty or "value" not in df.columns:
            output.append("ℹ️  Không có dữ liệu.")
            continue
        mean_val = df["value"].mean()
        min_val  = df["value"].min()
        max_val  = df["value"].max()
        n        = len(df)
        latest_row = df.iloc[-1]
        latest_val = latest_row["value"]
        latest_ts = latest_row["ts"].strftime('%Y-%m-%d %H:%M:%S')
        unit = ""
        for k, v in THRESHOLDS.items():
            if k in key_lower:
                unit = v["unit"]
                break
        output.append(f"🟢 MỚI NHẤT       : {latest_val:.3f} {unit} (Cập nhật lúc {latest_ts})")
        output.append(f"📊 Số điểm dữ liệu: {n}")
        output.append(f"📈 Cao nhất       : {max_val:.3f} {unit}")
        output.append(f"📉 Thấp nhất      : {min_val:.3f} {unit}")
        output.append(f"〰️  Trung bình     : {mean_val:.3f} {unit}")
        idx_max = df["value"].idxmax()
        idx_min = df["value"].idxmin()
        output.append(f"🕐 Đỉnh cao nhất lúc: {df.loc[idx_max, 'ts'].strftime('%Y-%m-%d %H:%M')}")
        output.append(f"🕐 Đỉnh thấp nhất lúc: {df.loc[idx_min, 'ts'].strftime('%Y-%m-%d %H:%M')}")
        trend = trend_description(df)
        output.append(f"📡 Xu hướng       : {trend}")
        alerts = detect_anomalies(df, key_lower)
        if alerts:
            output.append("🚨 Cảnh báo:")
            for a in alerts:
                output.append(f"      {a}")
        else:
            output.append("✅ Không phát hiện bất thường")
    output.append("\n" + "=" * 50)
    return "\n".join(output)

if __name__ == "__main__":
    # ================================================================
    # 🚀 MAIN LOOP
    # ================================================================
    try:
        client = NewsenseClient(BASE_URL, TB_USER, TB_PASS)
        all_devices = client.get_devices()
        device_name_to_id_map = {d["name"]: d["id"] for d in all_devices}
        print(f"✅ Đã tải {len(device_name_to_id_map)} thiết bị từ Newsense.")
    except Exception as e:
        print(f"❌ Không thể khởi tạo Newsense Client: {e}")
        client = None
        device_name_to_id_map = {}

    print("\n🤖 Chatbot Offline sẵn sàng. Gõ 'exit' để thoát.")
    print("💡 Ví dụ: 'GNSS 3 ngày gần đây'\n")

    while True:
        # 1. Bảo vệ toàn bộ quá trình bằng try...except để không bị sập vòng lặp
        try:
            query = input("\nBạn: ").strip()
            if not query:
                continue

            if query.lower() in ["exit", "quit", "q", "thoát"]:
                print("👋 Tạm biệt!")
                break

            if not client:
                print("❌ Client Newsense chưa khởi tạo.")
                continue

            # ── BƯỚC 1: Phân tích offline (không cần Gemini) ──────────────
            result = parse_query_offline(query)

            print("\n🧠 Kết quả phân tích (Offline):")
            print(json.dumps(result, ensure_ascii=False, indent=2))

            devices_to_plot = result.get("devices", [])
            start_date      = result.get("start_date")
            end_date        = result.get("end_date")

            if not devices_to_plot:
                print("ℹ️  Không tìm thấy thiết bị phù hợp.")
                print("   Gợi ý: Thêm tên vị trí cụ thể vào câu hỏi.")
                continue

            if not start_date or not end_date:
                print("⚠️  Không xác định được khoảng thời gian.")
                continue

            # ── BƯỚC 2: Lấy dữ liệu từ Newsense ──────────────────────────
            print("\n⏳ Đang tải dữ liệu từ Newsense...")
            fetched_data = []

            for device_info in devices_to_plot:
                device_name     = device_info.get("Device")
                data_key        = device_info.get("Tên biến")
                full_name_label = device_info.get("Tên thiết bị", device_name)

                if not device_name or not data_key:
                    continue

                device_id = device_name_to_id_map.get(device_name)
                if not device_id:
                    matches = difflib.get_close_matches(device_name, device_name_to_id_map.keys(), n=1, cutoff=0.8)
                    if matches:
                        print(f"   - Fuzzy match: '{device_name}' → '{matches[0]}'")
                        device_id = device_name_to_id_map[matches[0]]
                    else:
                        print(f"   - ⚠️ Không tìm thấy: '{device_name}'")
                        continue

                print(f"   - Đang lấy: {full_name_label} ({data_key})")

                # Bắt lỗi riêng khi tải API để tránh sập một thiết bị làm hỏng cả quá trình
                try:
                    df = client.get_timeseries(device_id, data_key, start_date, end_date)
                    if not df.empty:
                        fetched_data.append({
                            "label": f"{full_name_label} ({data_key})",
                            "data": df
                        })
                    else:
                        print(f"   - ℹ️  Không có dữ liệu cho {full_name_label}")
                except Exception as e:
                    print(f"   - ❌ Lỗi khi tải {device_name}: {e}")

            if not fetched_data:
                print("🚫 Không có dữ liệu để hiển thị biểu đồ/phân tích.")
                continue

            # ── BƯỚC 3: Vẽ biểu đồ ────────────────────────────────────────
            print("\n📈 Đang tạo biểu đồ...")
            num_plots = len(fetched_data)
            fig, axes = plt.subplots(num_plots, 1, figsize=(15, 5 * num_plots), squeeze=False)
            fig.suptitle(f"{query}", fontsize=16, y=1.01)

            for i, item in enumerate(fetched_data):
                df, label = item["data"], item["label"]
                ax = axes[i][0]
                ax.plot(df["ts"], df["value"], label=label, marker=".", linestyle="-", linewidth=1)
                ax.set_title(label, fontsize=12)
                ax.set_xlabel("Thời gian")
                ax.set_ylabel("Giá trị")
                ax.legend(loc="best")
                ax.grid(True, linestyle="--", linewidth=0.5)

            plt.tight_layout()
            plt.show()

            # FIX QUAN TRỌNG: Xóa biểu đồ khỏi bộ nhớ Colab để tránh treo cho lần nhập sau
            plt.close('all')

            # ── BƯỚC 4: Phân tích offline (không cần Gemini) ──────────────
            analyze_data_offline(fetched_data, query)

            print("\n" + "✨" * 25)
            print("✅ Đã xử lý xong! Mời bạn cuộn xuống và nhập câu hỏi tiếp theo.")
            print("✨" * 25)

        except Exception as e:
            # Nếu có lỗi ngầm xảy ra ở bất kỳ đâu, in ra lỗi và tiếp tục vòng lặp
            print(f"\n❌ LỖI HỆ THỐNG: {e}")
            import traceback
            traceback.print_exc()
            print("🔄 Chatbot đã tự động phục hồi. Bạn có thể thử câu hỏi khác.")

